[package]
name = "gabelstaplerwm"
version = "0.1.0"
authors = ["Inokentiy Babushkin <inokentiy.babushkin@googlemail.com>"]

[dependencies]
libc = "*"
env_logger = "0.3.3"
log = "*"
xcb = { version = "0.7.3", features = ["xkb"] }
