[package]
name = "gabelstaplerwm"
version = "0.5.0"
authors = ["Inokentiy Babushkin <inokentiy.babushkin@googlemail.com>"]
description = "A semidynamic tiling window manager using XCB"
documentation = "https://ibabushkin.github.io/rustdoc/gabelstaplerwm/"
homepage = "https://ibabushkin.github.io/"
repository = "https://github.com/ibabushkin/gabelstaplerwm"
readme = "README.md"
keywords = ["xcb", "window manager", "X"]
license = "BSD3"

[features]
default = ["parallel-resizing"]
parallel-resizing = []

[dependencies]
libc = "*"
env_logger = "*"
log = "*"
# xcb = { version = "0.7.5", features = ["xkb", "randr"] }
xcb = { git = "https://github.com/ibabushkin/rust-xcb/", branch = "master", features = ["xkb", "randr"] }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
